Parameters:
  AWSS3BUCKET:
    Type: String
    Description: "S3 Bucket where Lambda deployment packages are stored"
  HOST:
    Type: String
    Description: "Database host"
  USERDB:
    Type: String
    Description: "Database user"
  PASSWORD:
    Type: String
    Description: "Database password"
  DATABASE:
    Type: String
    Description: "Database name"
  DBTABLE:
    Type: String
    Description: "Database table name"
  SECURITYGROUP:
    Type: String
    Description: "Security Group ID for Lambda functions"
  SUBNETIDS:
    Type: CommaDelimitedList
    Description: Lista de Subnets

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"

  DataBaseCreation:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: DataBaseCreation
      Runtime: nodejs18.x
      Code:
        # S3Key: ${AWSS3BUCKET}/lambda-artifacts/lambda-post.zip
        S3Bucket: !Ref AWSS3BUCKET
        S3Key: lambda-artifacts/DataBaseCreation.zip
      Environment:
        Variables:
          DB_HOST: !Ref HOST
          DB_USER: !Ref USERDB
          DB_PASSWORD:   !Ref PASSWORD
          DB_NAME: !Ref DATABASE
      VpcConfig:
        SecurityGroupIds:
          - !Ref SECURITYGROUP  # Debes definir este security group en tus resources
        SubnetIds:  !Ref SUBNETIDS

  CheckDataBase:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: CheckDataBase
      Runtime: nodejs18.x
      Code:
        # S3Key: ${AWSS3BUCKET}/lambda-artifacts/lambda-post.zip
        S3Bucket: !Ref AWSS3BUCKET
        S3Key: lambda-artifacts/CheckDataBase.zip
      Environment:
        Variables:
          DB_HOST: !Ref HOST
          DB_USER: !Ref USERDB
          DB_PASSWORD:   !Ref PASSWORD
          DB_NAME: !Ref DATABASE
      VpcConfig:
        SecurityGroupIds:
          - !Ref SECURITYGROUP  # Debes definir este security group en tus resources
        SubnetIds:  !Ref SUBNETIDS

  GetPersonLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: GetPersonLambda
      Runtime: nodejs18.x
      Code:
        # S3Key: ${AWSS3BUCKET}/lambda-artifacts/lambda-post.zip
        S3Bucket: !Ref AWSS3BUCKET
        S3Key: lambda-artifacts/GetPersonLambda.zip
      Environment:
        Variables:
          DB_HOST: !Ref HOST
          DB_USER: !Ref USERDB
          DB_PASSWORD:   !Ref PASSWORD
          DB_NAME: !Ref DATABASE
          DB_TABLE: !Ref DBTABLE
      VpcConfig:
        SecurityGroupIds:
          - !Ref SECURITYGROUP  # Debes definir este security group en tus resources
        SubnetIds:  !Ref SUBNETIDS

  PutPersonLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: PutPersonLambda
      Runtime: nodejs18.x
      Code:
        # S3Key: ${AWSS3BUCKET}/lambda-artifacts/lambda-post.zip
        S3Bucket: !Ref AWSS3BUCKET
        S3Key: lambda-artifacts/PutPersonLambda.zip
      Environment:
        Variables:
          DB_HOST: !Ref HOST
          DB_USER: !Ref USERDB
          DB_PASSWORD:   !Ref PASSWORD
          DB_NAME: !Ref DATABASE
          DB_TABLE: !Ref DBTABLE
      VpcConfig:
        SecurityGroupIds:
          - !Ref SECURITYGROUP  # Debes definir este security group en tus resources
        SubnetIds:  !Ref SUBNETIDS

  DeletePersonLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: DeletePersonLambda
      Runtime: nodejs18.x
      Code:
        # S3Key: ${AWSS3BUCKET}/lambda-artifacts/lambda-post.zip
        S3Bucket: !Ref AWSS3BUCKET
        S3Key: lambda-artifacts/DeletePersonLambda.zip
      Environment:
        Variables:
          DB_HOST: !Ref HOST
          DB_USER: !Ref USERDB
          DB_PASSWORD:   !Ref PASSWORD
          DB_NAME: !Ref DATABASE
          DB_TABLE: !Ref DBTABLE
      VpcConfig:
        SecurityGroupIds:
          - !Ref SECURITYGROUP  # Debes definir este security group en tus resources
        SubnetIds:  !Ref SUBNETIDS

  PostPersonLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: PostPersonLambda
      Runtime: nodejs18.x
      Code:
        S3Bucket: !Ref AWSS3BUCKET
        S3Key: lambda-artifacts/PostPersonLambda.zip
      Environment:
        Variables:
          DB_HOST: !Ref HOST
          DB_USER: !Ref USERDB
          DB_PASSWORD:   !Ref PASSWORD
          DB_NAME: !Ref DATABASE
          DB_TABLE: !Ref DBTABLE

      VpcConfig:
        SecurityGroupIds:
          - !Ref SECURITYGROUP  # Debes definir este security group en tus resources
        SubnetIds:  !Ref SUBNETIDS

  PersonsApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PersonsAPI

  PersonsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PersonsApi
      ParentId: !GetAtt [PersonsApi, RootResourceId]
      PathPart: persons

  PersonIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PersonsApi
      ParentId: !Ref PersonsResource
      PathPart: "{id}"

  GetPersonsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref PersonsResource
      RestApiId: !Ref PersonsApi
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPersonLambda.Arn}/invocations
            - Region: ${AWS::Region}
      MethodResponses:
        - StatusCode: 200

  PutPersonsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: PUT
      ResourceId: !Ref PersonIdResource
      RestApiId: !Ref PersonsApi
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PutPersonLambda.Arn}/invocations
            - Region: ${AWS::Region}
      MethodResponses:
        - StatusCode: 200

  DeletePersonsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: DELETE
      ResourceId: !Ref PersonIdResource
      RestApiId: !Ref PersonsApi
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeletePersonLambda.Arn}/invocations
            - Region: ${AWS::Region}
      MethodResponses:
        - StatusCode: 200

  PostPersonsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref PersonsResource
      RestApiId: !Ref PersonsApi
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostPersonLambda.Arn}/invocations
            - Region: ${AWS::Region}
      MethodResponses:
        - StatusCode: 201

  LambdaInvokePermissionGet:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GetPersonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PersonsApi}/*/GET/persons"

  LambdaInvokePermissionPost:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PostPersonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PersonsApi}/*/POST/persons"

  LambdaInvokePermissionPut:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PutPersonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PersonsApi}/*/PUT/persons/*"


  LambdaInvokePermissionDelete:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DeletePersonLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PersonsApi}/*/DELETE/persons/*"

  PersonsApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref PersonsApi
      StageName: prod
      DeploymentId: !Ref PersonsApiDeployment

  PersonsApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetPersonsMethod
      - PostPersonsMethod
      - PutPersonsMethod
      - DeletePersonsMethod
    Properties:
      RestApiId: !Ref PersonsApi

Outputs:
  APIURL:
    Description: "URL of the API Gateway"
    Value: !Sub "https://${PersonsApi}.execute-api.${AWS::Region}.amazonaws.com/prod"