name: Flujo de trabajo manual

on:
  workflow_dispatch:
    inputs:
      nombre_rama:
        description: 'Rama en la que se ejecutará'
        required: true
        default: 'main' 

jobs:
  ejecutar_trabajo:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje de confirmación
        run: echo "El flujo de trabajo se ha ejecutado manualmente en la rama ${{ github.event.inputs.nombre_rama }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: List archivos y directorio
        run: |
          pwd
          ls -l
          ls -l lambda-tests/

      - name: Ejecuta tests de Lambda desde archivos
        run: |
          for testfile in lambda-tests/*.json; do
            FUNC_NAME=$(basename "$testfile" .json)
            echo "Probando función $FUNC_NAME con payload de $testfile"
            echo ""
          done
