name: Create S3,Build and Upload Lambda to S3

on:
  push:
    paths:
      - lambdas/**
      - .github/workflows/upload-lambdas.yml

  workflow_run:
    workflows: ["Create S3,Build and Upload Lambda to S3"]  # El nombre definido en 'name:' del otro workflow
    types:
      - completed

jobs:

  deploy-lambda:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Lambda function
        run: |
          mkdir lambdas-zipped
          cd lambdas
          for d in */ ; do
            zip -r "../lambdas-zipped/${d%/}.zip" "$d"
          done


      - name: Create S3 bucket (if not exists) 
        env:
          AWS_S3_BUCKET: ${{ secrets.LAMBDA_ARTIFACT_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} 
        run: |
          if aws s3api head-bucket --bucket "$AWS_S3_BUCKET" 2>/dev/null; then
            echo "Bucket $AWS_S3_BUCKET already exists."
          else
            aws s3api create-bucket --bucket "$AWS_S3_BUCKET" --region "$AWS_REGION" \
              --create-bucket-configuration LocationConstraint="$AWS_REGION"
            echo "Bucket $AWS_S3_BUCKET created."
          fi

      - name: Upload zip to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: ${{ secrets.LAMBDA_ARTIFACT_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ./lambdas-zipped          # Root (will look for lambda.zip)
          DEST_DIR: lambda-artifacts

      - name: Create Lambda functions and API GatewayId
        run: |
          aws cloudformation deploy \
            --template-file Iac/api.yaml \
            --stack-name lambda-api-stack-$(date +%Y%m%d%H%M%S) \
            --parameter-overrides AWS_S3_BUCKET=${{ secrets.LAMBDA_ARTIFACT_BUCKET }} \
            --capabilities CAPABILITY_NAMED_IAM

      # Update this or the next step as needed for CloudFormation deployment
